### ISSUE TITLE
Tests check that progress is made

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#1097]
Right now all our Validating tests pass even if there is a bug that causes a timeout because the tests don't check for progress being made when it should be.

The test harness doesn't know about any previous rounds which is why we don't actually check this.  We should probably have some cache of previous node states so when we implement: https://github.com/EspressoSystems/HotShot/issues/1068 we can add checks for based on more than just the current state.

**Comment by elliedavidson** [comment]
Note: This can occur in the cast where a leader sends out a proposal for view v, replicas vote on it, but they do not receive a proposal for view v + 1 within the timeout.
