### ISSUE TITLE
Check transactions once StateCommitment/MaybeState is cleaned up

### ISSUE THREAD

**Issue by DieracDelta** [EspressoSystems/HotShot#1167]
We can't exactly check that the transactions all match those submitted because of a type error. We ONLY have `MaybeState` and we need `State`. unless we specialize, this won't happen. so waiting on refactor for this code is below:
```rust
        let next_state /* : Option<_> */ = {
        if let Some(last_leaf) = ctx.prior_round_results.iter().last() {
            if let Some(parent_state) = last_leaf.agreed_state {
                let mut block = <TYPES as NodeType>::StateType::next_block(Some(parent_state.clone()));
            }
        }
    };
```

**Comment by elliedavidson** [comment]
@DieracDelta is this issue still relevant?  Or can we close it?

**Comment by DieracDelta** [comment]
Not relevant anymore. Let's close it.
