### ISSUE TITLE
Create a diagram for DA and sequencing consensus

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/HotShot#1195]
Create a flow to show the logic of the leader, replica, and DA member, including how the proposals, votes, and certificates work.

This will be used by the product team in partner convos.

**Comment by elliedavidson** [comment]
@shenkeyao do we still need this issue?

**Comment by shenkeyao** [comment]
> @shenkeyao do we still need this issue?

Not needed. I'll close this.
