### ISSUE TITLE
Integrate aggregate signature + bit-vector QC validation trait

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/HotShot#1208]
- [x] Integrate [hotshot-primitives](https://github.com/EspressoSystems/hotshot-primitives) with [jellyfish-0.4.0-pre.0](https://github.com/EspressoSystems/jellyfish/releases/tag/0.4.0-pre.0).
- [x] Add [dependency of `hotshot-primitives`](https://github.com/EspressoSystems/hotshot-primitives/tree/update_jellyfish_0.4.0_pre.0) to hotshot.
- [x] Define the content of the QC (i.e. which message is signed)
- [x] Instantiation of [QC validation trait](https://github.com/EspressoSystems/hotshot-primitives/blob/00d0a3ce966d0f0fc4cb1593ba61bb57ecc36249/src/quorum_certificate.rs).
- [x] Change signature scheme from [BLSSignatureScheme](https://jellyfish.docs.espressosys.com/jf_primitives/signatures/bls_over_bls12381/struct.BLSSignatureScheme.html#) to [BLSOverBN254CurveSignatureScheme](https://jellyfish.docs.espressosys.com/jf_primitives/signatures/bls_over_bn254/struct.BLSOverBN254CurveSignatureScheme.html), also added [KeyPair](https://github.com/EspressoSystems/jellyfish/commit/c07a87f1469aaf761a3e909e9bd8b692b8ed6740#diff-1ba37046f2f9c0ac409fdb3f45b9700288ac2c5e87a174408ed5ec5448d39df0R265).
- [x] Update partial signing on proposals, votes, and messages for QuorumExchange and CommitteeExchange.
- [x] Make the commitment a fixed size. Relevent to https://github.com/EspressoSystems/hotshot-primitives/pull/27#discussion_r1186187429. Create this [issue](https://github.com/EspressoSystems/HotShot/issues/1320).
- [x] Update the way of forming `Encoded Signature`.
- [x] Add [verify](https://github.com/EspressoSystems/jellyfish/blob/3e8b7d6d1908345951e299eed63e656420e4e401/primitives/src/signatures/bls_over_bn254.rs#L120) when leader receives signature.
- [x] Update vote assembling: do assembling when the number of votes achieves a threshold.
- [x] Update QC aggregation check.
- [x] Add bit vector.
- [x] Add the verification of uniqueness before `assemble()`.
- [x] Depend on the newest `hotshot-primitives`.
-  ~Integration tests.~
- [x] Clean up.

The QC validation trait and the naive instantiation using a bit vector is [implemented](https://github.com/EspressoSystems/hotshot-primitives/blob/00d0a3ce966d0f0fc4cb1593ba61bb57ecc36249/src/quorum_certificate.rs).
Instantiate this trait in the hotshot validation logic once the content of a qc message is defined.

cc @elliedavidson

**Comment by philippecamacho** [comment]
Blocked by: https://github.com/EspressoSystems/hotshot-primitives/issues/31

**Comment by dailinsubjam** [comment]
- [ ] Integrate [hotshot-primitives](https://github.com/EspressoSystems/hotshot-primitives) with [jellyfish-0.4.0](https://github.com/EspressoSystems/jellyfish/releases/tag/0.4.0-pre.0).

**Comment by dailinsubjam** [comment]
- [ ] Add [dependency of `hotshot-primitives`](https://github.com/EspressoSystems/hotshot-primitives/tree/update_jellyfish_0.4.0_pre.0) to hotshot.

**Comment by dailinsubjam** [comment]
https://github.com/EspressoSystems/HotShot/commit/b7aa0104865faab04230cf9d2c5510f6583b63bd

**Comment by dailinsubjam** [comment]
Related to https://github.com/EspressoSystems/hotshot-primitives/pull/64
