### ISSUE TITLE
Authenticate the DHT

### ISSUE THREAD

**Issue by DieracDelta** [EspressoSystems/HotShot#1277]
The DHT should be authenticated. This means that the staking key should sign the data stored. This includes both the public key mapping and the routing table. We want this to prevent eclipse attacks where all a nodes peers will be controlled by other nodes. This is the other half of https://github.com/EspressoSystems/HotShot/issues/678. which forces a more even DHT distribution. To this end:

- Check that this isn't already done by the kademlia implementation in libp2p-rust. I know libp2p-rust exposes a way to extract the peerid of the node(s) with the DHT entry. Maybe we can use that somehow.
- If not already implemented, fork the DHT protocol to add this.

**Comment by elliedavidson** [comment]
@DieracDelta is this issue still relevant? Or can we close it?

**Comment by DieracDelta** [comment]
This is a question we should answer and write down explicitly. We need to see if libp2p does this and make sure it does. If it doesn't, we'll need to add it. This might be a good task for @rob-maron to familiarize with libp2ps implementation of kademlia  if he has time.

**Comment by rob-maron** [comment]
Closed in favor of #3540
