### ISSUE TITLE
Remove `Sync` from PassType  and SendableStream

### ISSUE THREAD

**Issue by DieracDelta** [EspressoSystems/HotShot#1310]
If possible, remove `Sync` from PassType  and SendableStream. If not possible, document why. This seems like it should be overly restrictive.

**Comment by elliedavidson** [comment]
@DieracDelta is this issue still relevant?

**Comment by DieracDelta** [comment]
Nope. I tried to do this, and it wasn't possible. It's because we need to pass stuff between threads.
