### ISSUE TITLE
Tests for Nodes Leaving the Nework

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#1466]
This is related to #1464 but specifically we need a test which can shows we make expected progress when one or more nodes leaves the network in an arbitrary round.  This test doesn't need to include the node coming back to the network

**Comment by DieracDelta** [comment]
https://github.com/EspressoSystems/HotShot/blob/2830bf17b95b790791f99d3160a187d3119c1401/testing/tests/basic.rs#L24 this exists but doesn't pass.
