### ISSUE TITLE
Signature Aggregation Macro Task

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#1542]
This task encompasses tasks related to supporting signature aggregation in HotShot

- [x] https://github.com/EspressoSystems/HotShot/issues/1513
- [x] https://github.com/EspressoSystems/HotShot/issues/1498

**Comment by dailinsubjam** [comment]
Add API Change after hotshot-primitives moved into hotshot https://github.com/EspressoSystems/HotShot/issues/1570
