### ISSUE TITLE
Define a concept of a block header

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/HotShot#1566]
In the sequencer, we have introduced the concept of an [app-specific header](https://github.com/EspressoSystems/espresso-sequencer/blob/main/sequencer/src/block.rs#L18), which clients can download if they want authenticated metadata like timestamps but not the whole block payload. This concept could be enshrined in HotShot itself, which would allow us to implement endpoints that deal with headers in the generic query service, instead of specifically for the sequencer node. This would also allow us to include the block number in the header and header commitment, which would simplify a lot of interfaces. We currently can't do this because the application doesn't know the block number when it is asked to create the next block.

**Comment by shenkeyao** [comment]
Requirements
- Header constructor takes the previous leaf (includes the previous header) and payload commitment (provided by DA leader task)
- Header must commit to the payload using a VID commitment
    - Trait function to get the payload commitment from a header
- Header must be retrievable by the VID commitment
- Header includes fees, latest Ethereum bloc, etc.
- Only header is included in proposals; payload is sent to DA committee only

**Comment by jbearer** [comment]
> Header must be retrievable by the VID commitment

I missed this in the meeting, I'm not sure exactly what this means @shenkeyao @elliedavidson

**Comment by elliedavidson** [comment]
I'm unsure as well

**Comment by shenkeyao** [comment]
> > Header must be retrievable by the VID commitment
> 
> I missed this in the meeting, I'm not sure exactly what this means @shenkeyao @elliedavidson

@jbearer This looks like a duplication of the previous point, “Header must commit to the payload using a VID commitment.”

I think we could remove this requirement from the list, but @elliedavidson could I get the link to the meeting recording? Then I’ll double check this from the recording.

**Comment by shenkeyao** [comment]
> > > Header must be retrievable by the VID commitment
> > 
> > 
> > I missed this in the meeting, I'm not sure exactly what this means @shenkeyao @elliedavidson
> 
> @jbearer This looks like a duplication of the previous point, “Header must commit to the payload using a VID commitment.”
> 
> I think we could remove this requirement from the list, but @elliedavidson could I get the link to the meeting recording? Then I’ll double check this from the recording.

I've checked the recording and "retrievable by the VID commitment" wasn't mentioned. I've removed it from the list.
