### ISSUE TITLE
API Change after hotshot-primitives moved into hotshot

### ISSUE THREAD

**Issue by dailinsubjam** [EspressoSystems/HotShot#1570]

**Comment by ggutoski** [comment]
As Alex has [helpfully explained](https://espresso.zulipchat.com/#narrow/stream/311646-Consensus/topic/hotshot-compat.20branches/near/387100078) everything that hotshot needs from hotshot-primitives has already been ported to hotshot in packages `types`, `crates/hotshot-qc`, and `crates/hotshot-stake-table`.

Currently the only use of hotshot-primitives is in the `types` package. (Yay!) However, both `hotshot-qc` and `hotshot-stake-table` depend on `types`. So switching from hotshot-primitives to these new packages creates a circular dependency.

I propose to eliminate this circular dependency by moving everything we need from `hotshot-qc` and `hotshot-stake-table` into `types`. (Presumably, anything that remains can simply be deleted?)

An alternative is to instead move the offending code out of `types`.  The offending code is in a single file: `bn254_pub.rs`. Is this something that should live in the `types` package? If not then where's the best place to put it?

**Comment by ggutoski** [comment]
On further discussion we decided to leave trait `SignatureKey` in `hotshot-types` and move all impls (ie. `bn254`) to a new crate under `crates/hotshot-signature-key`.
