### ISSUE TITLE
Inherited workspace dependencies

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1591]
Several dependencies are copied in multiple `Cargo.toml` package files in the hotshot workspace. Example:

```toml
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", branch = 'hotshot-compat'} # rev = "470a833" for branch = 'hotshot-compat'
```

Perhaps it's better to use the dependency inheritance feature of cargo to allow us to specify such dependencies in only one place. According to [The Cargo Book](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) all inherited dependencies are put into a new `[workspace.dependencies]` section of the root-level `Cargo.toml`.

Any reason not to do this?

**Comment by DieracDelta** [comment]
+1 +1 +1
