### ISSUE TITLE
Update BN254 SignatureKey name to reflect the curve and signature scheme

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#1592]
As mentioned here: https://github.com/EspressoSystems/HotShot/pull/1589#discussion_r1300682320

E.g. something like BLSVerKey (as mentioned in the issue above)

**Comment by dailinsubjam** [comment]
Done in https://github.com/EspressoSystems/HotShot/pull/1767/commits/9215a7ca316c553447643bddb68761fba4bfc14a .
