### ISSUE TITLE
Update libp2p to use QUIC

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#1624]
https://github.com/libp2p/rust-libp2p/blob/master/transports/quic/CHANGELOG.md

**Comment by DieracDelta** [comment]
I think this is a duplicate of https://github.com/EspressoSystems/HotShot/issues/725. Should I close #725?

**Comment by elliedavidson** [comment]
> I think this is a duplicate of #725. Should I close #725?

Yes, that sounds good.
