### ISSUE TITLE
Secure SRS for VID

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1686]
Currently we use jellyfish's `gen_srs_for_testing`, even in production. Obviously, we shouldn't do that.

[EDIT: remove `test-srs` feature flag from `Cargo.toml`, too!]

In an ideal world this SRS would be loaded from a config file. Better yet, a default SRS could be hard-coded so as to save work on io/parse.

**Comment by ggutoski** [comment]
dup of #1836

**Comment by ggutoski** [comment]
Perhaps the SRS should be in the sequencer. Hotshot should know nothing about that.

**Comment by alxiong** [comment]
we already have `crs` crate to load Aztec's SRS, right? what else do we want to achieve here? eval form for VID or?

**Comment by alxiong** [comment]
sure thing, here's the one-liner `crs::aztec20::kzg10_setup(degree + 2)` (the +2 is specific to our turboplonk design), feel free to mimic this.

https://github.com/search?q=repo%3AEspressoSystems%2Fespresso-sequencer+crs%3A%3Aaztec&type=code

**Comment by ggutoski** [comment]
@akonring could help in my absence

**Comment by ggutoski** [comment]
Also need to remove `test-srs` feature flag from Cargo.toml too!
