### ISSUE TITLE
Distinguish VID leader from DA leader?

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1699]
Currently VID leader = DA leader. Most (all?) the time these leaders are the same node. Shall we allow them to be different?

https://github.com/EspressoSystems/HotShot/blob/b1658b1708f716633cf410aa9d72c39350235f66/crates/task-impls/src/network.rs#L247

**Comment by shenkeyao** [comment]
We make the consensus leader and DA leader the same, so I would assume the VID leader is also the same node. Curious if there are benefits to distinguish them.
