### ISSUE TITLE
[TECH_DEBT] - ark-serialize dependency should use workspace

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1700]
https://github.com/EspressoSystems/HotShot/blob/58690984bca20c7c60cdabc7dd6dbf5bd6d899f2/crates/types/Cargo.toml#L18-L20

**Comment by alxiong** [comment]
why is this marked as closed while it's not using `{ workspace = true}` 

@jbearer

**Comment by shenkeyao** [comment]
> why is this marked as closed while it's not using `{ workspace = true}`
> 
> @jbearer

@alxiong I just did a quick check, looks like the `ark-serialize` in the specified path is indeed using `workspace = true`.

All other `ark-serialize`s in HotShot also seem correct, except the one in `HotShot/Cargo.toml` which is using `ark-serialize = "0.4"`. Let me reopen this issue and send a quick fix for the remaining one.
