### ISSUE TITLE
Generic-array should not be an explicit dependency

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1850]
Currently `generic-array` is an explicit direct dependency. All our use of `generic-array` is inherited from upstream RustCrypto crates such as blake3, sha3, digest, etc. Thus, the version of `generic-array` that we use should be whatever's used by these upstream crates. Thus, we should not list it as an explicit direct dependency.

Unfortunately, we need `serde` for `generic-array` and I don't know how to get it without listing `generic-array` as an explicit dependency. This is an insidious hack because it means that we must take care to always keep the version of `generic-array` we list in `Cargo.toml` consistent with whatever's used upstream.

Anyone have a better solution? @DieracDelta

**Comment by DieracDelta** [comment]
@ggutoski what are we using that requires serde for generic-array?

**Comment by ggutoski** [comment]
> @ggutoski what are we using that requires serde for generic-array?

I think we're serdeing structs that contain hash output which is a generic array

**Comment by ggutoski** [comment]
Here's an example of direct usage of `GenericArray` that should be eliminated:
https://github.com/EspressoSystems/HotShot/blob/e78b628d8d3ec18227beffa2437d8e4a93b59dbf/crates/types/src/traits/qc.rs#L45
This is not a direct answer to this question https://github.com/EspressoSystems/HotShot/issues/1850#issuecomment-1776160559 because there's no serde here. I'll post more sometime later.
