### ISSUE TITLE
memory_network_test_in_flight_message_count hangs nondeterministically on main branch

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#1857]
Make it easier to reproduce: add the following to your `justfile`:
```
test_memory_network:
  echo Testing the DA task with async std executor
  ASYNC_STD_THREAD_COUNT=1 cargo test --lib --bins --tests --benches --workspace --no-fail-fast memory_network -- --test-threads=1 --nocapture
```
Then run
```
just async_std test_memory_network
```
Need to run ~5 times to observe the test hang, otherwise it passes with no error.

Assigning to @rob-maron because he was the last person to touch this code. 😄

**Comment by rob-maron** [comment]
I have what I believe to be the fix in here https://github.com/EspressoSystems/HotShot/pull/1847
