### ISSUE TITLE
[hotshot-state-prover] Prover service implementation

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/HotShot#1988]
Concretely,
- Fetching stake table from L1
- Fetching Schnorr signatures and finalized hotshot state (the signed message) from DA services of HotShot
- Proof generation (done in #1985 )
- Submit serialized proofs to L1

**Comment by mrain** [comment]
Moved to https://github.com/EspressoSystems/hotshot-prover-service/issues/1
