### ISSUE TITLE
Vote logic for VID cert

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/HotShot#2067]

**Comment by dailinsubjam** [comment]
Some notes from pair programming meeting:

- currently we’re doing VID computations but not using them in consensus
- NOT in scope for this issue: deliver different shares to different storage nodes
- Each replica node does not vote on a proposal until it has seen it’s VID share
    - QC = VIDCert
- Handle VidShareRecv in the VID task
- Handle VIDCertRecv in the consensus task
- Get rid of VIDVote events and VIDCert events
- Tasks for this issue:
    - Handle VIDShareRecv event in the VID task
        - Store that you have gotten a VID share for a specific block
        - clarify: for this issue VIDShareRecv contains ALL shares. The task to deliver one share to each node is a separate issue
    - Update vote logic so replicas don’t vote until they’ve seen a VIDShare

**Comment by dailinsubjam** [comment]
- When a node receives a `QuorumProposal` it does not vote until all of the following conditions are met
    - It has seen a DAC, `vote_if_able()` will decide.
    - It has seen its VID share (not VIDCert) --> This part this issue will need to implement. Will add to `vote_if_able()`.
