### ISSUE TITLE
Remove commitment computation for `BlockPayload`

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/HotShot#2072]
Currently `BlockPayload` implements `fn commit` which takes a VID commitment computed from the payload construction. We should get or store the VID commitment in HotShot instead, to avoid the computation waste in the app-specific implementation.

Related discussions: https://github.com/EspressoSystems/espresso-sequencer/pull/756#discussion_r1394811330.

**Comment by ggutoski** [comment]
A long time ago I tried to remove `Committable` from `BlockPayload` but it was infeasible. Perhaps now that the refactor is near done this might be feasible.
