### ISSUE TITLE
[LIBP2P] Parameterize the DHT timeout

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2088]
### Describe the task
* What is the reason for this task? 

Right now, the DHT timeout as specified in the Libp2p network is hardcoded and optimal for 10-30 nodes. We want to parameterize this so we can change it based on the number of actual nodes in the run. This is especially helpful for testing purposes.

* What work will need to be done to complete this task?  If this is unknown, describe what information is needed to determine the work needed

To complete this task, we will need to 
1. Add the DHT timeout to the testing metadata.
2. Add the DHT timeout to the example parameters

Both of these just require adding and using a simple parameter. May require working a bit through the codebase to chase down anything.

### Acceptance Criteria
Describe the acceptance criteria needed for this task to be closed
* List any sub-tasks that need to be completed 
* List which tests are applicable to this change.  List any new tests that need to be added for this 

- [ ] Add the DHT timeout to the testing metadata.
- [ ] Add the DHT timeout to the example parameters

### Checklist
- [x] Label this issue appropriately.  If this issue is created by an outside contributor, label it `outside-issue`. Unless a task is labeled `low-priority`, `outside-issue`, or `tech-debt` it must include a `sprint` label and be associated with the `sprint` milestone. 
- [x] If this is a macro task, add [MACRO] to the front of the issue name
- [x] If this is not a macro task, add [<MACRO_TASK_SHORT_NAME>] to the front of the issue name. Then add a link to the macro task it is associated with.  Every non-macro task must be associated with a macro task unless it is labeled `low-priority`,`tech-debt`, or `outside-issue`. 
- [x] Add this issue to the appropriate project boards, unless it is labeled `low-priority`, `outside-issue`, or `tech-debt` 
- [x] Assign this issue to the appropriate person, if applicable.

**Comment by bfish713** [comment]
We set this pretty high during investigations, we should work it down to something more reasonable now that the issues are resolved.
