### ISSUE TITLE
[Combined network] Improve the network switching algorithm

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2089]
### Describe the task
* What is the reason for this task? 

Right now the combined network switching logic is a bit primitive. It uses a globally configurable constant to bound the number of failed messages before ignoring and only sending over the p2p network. We want to allow it to work with a more flaky network definition, where 1 message might fail every N times. 

* What work will need to be done to complete this task?  If this is unknown, describe what information is needed to determine the work needed

The work is to come up with and implement an algorithm that makes this issue better. One option as specified by @DieracDelta is to track a weighted sum of failures, where newer CDN message failures cost more than older ones.

Related comment: https://github.com/EspressoSystems/HotShot/pull/1994#discussion_r1398293213

### Acceptance Criteria
Describe the acceptance criteria needed for this task to be closed
* List any sub-tasks that need to be completed 
* List which tests are applicable to this change.  List any new tests that need to be added for this task

- [ ] Come up with an algorithm to improve the switching logic.
> I wonder if this covers the case of a very flakey primary network. For example, suppose a message goes through the primary network once every `COMBINED_NETWORK_PRIMARY_FAILURES - 1` times. Out of scope for this PR, but it might be worthwhile tracking a weighted sum describing the health of the network where more recent failures/successes count more heavily than older attempts. This would allow us to choose libp2p directly when the overall network is dropping _most_ packets instead of just consecutive packets.

- [ ] Implement the algorithm to improve the switching logic

### Checklist
- [x] Label this issue appropriately.  If this issue is created by an outside contributor, label it `outside-issue`. Unless a task is labeled `low-priority`, `outside-issue`, or `tech-debt` it must include a `sprint` label and be associated with the `sprint` milestone. 
- [x] If this is a macro task, add [MACRO] to the front of the issue name
- [ ] If this is not a macro task, add [<MACRO_TASK_SHORT_NAME>] to the front of the issue name. Then add a link to the macro task it is associated with.  Every non-macro task must be associated with a macro task unless it is labeled `low-priority`,`tech-debt`, or `outside-issue`. 
- [x] Add this issue to the appropriate project boards, unless it is labeled `low-priority`, `outside-issue`, or `tech-debt` 
- [x] Assign this issue to the appropriate person, if applicable.

**Comment by bfish713** [comment]
marking this as stretch because this was improved during the sprint but we can probably do more
