### ISSUE TITLE
Add support for light client state prover

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/HotShot#2090]
_this is a parent issues explaining the design & overall progress, subtasks should be created for each individual points._

Replica:

- When register on the stake table in L1, generate a Schnorr key pair (besides the HotShot’s consensus key which is `bls-over-bn254`)
- On every new finalized block, if it leads to a new finalized `LightClientState` then the replica sign the new state and store the Schnorr signature locally and send one copy to the CDN
    - The copy are sent alongside the normal consensus vote in that round (i.e. no extra round is required)
- Garbage collect: replicas also subscribe event stream from `LightClient.sol` on L1, when `event NewFinalizedState` is emitted, replicas delete all signatures on that state and even older ones. We could also add a worst-case storage cap on how long these signatures would be kept before being pruned.
    - Assume a worst-case delay on L1 light client update of 5 hour (and assume 3 sec block time), each replica only keeps ~6k * 64 = 0.38MB of signature data, ~6k * 208 = 1.25MB of state/message data locally.
- Pessimistic case: in case of CDN failures, replica would send over their signatures to the prover
    - Since we don’t want anyone to DOS replica, how do we prevent that?

CDN:

- Index all Schnorr signatures received by the `block_height` field of the signed message, and cached them
- Upon request from the `hotshot-state-prover` on a specific block height, serve all Schnorr signatures cached
- Garbage collect: same as that of Replica

cc @jbearer @philippecamacho @fkrell @chancharles92 

smaller issues:
- [x] #2119
- [x] #2120
- [x] #2121

**Comment by philippecamacho** [comment]
> Pessimistic case: in case of CDN failures, replica would send over their signatures to the prover
Since we don’t want anyone to DOS replica, how do we prevent that?

Is this problem not similar to the problem DoS against replicas by [trigerring VID shares reconstruction](https://www.notion.so/espressosys/R-D-Meeting-0b0803b1f6044fb1a5cfae3f4f679125?pvs=4#d476988c210f4e8d83757b3f9372a8e7)? IIUC we reached the conclusion that this is a [fundamental issue in distributed systems in general](https://www.notion.so/espressosys/R-D-Meeting-0b0803b1f6044fb1a5cfae3f4f679125?pvs=4#bd473d61a6614a9393eac8068cd34e7b).

**Comment by mrain** [comment]
> > Pessimistic case: in case of CDN failures, replica would send over their signatures to the prover
> > Since we don’t want anyone to DOS replica, how do we prevent that?
> 
> Is this problem not similar to the problem DoS against replicas by [trigerring VID shares reconstruction](https://www.notion.so/espressosys/R-D-Meeting-0b0803b1f6044fb1a5cfae3f4f679125?pvs=4#d476988c210f4e8d83757b3f9372a8e7)? IIUC we reached the conclusion that this is a [fundamental issue in distributed systems in general](https://www.notion.so/espressosys/R-D-Meeting-0b0803b1f6044fb1a5cfae3f4f679125?pvs=4#bd473d61a6614a9393eac8068cd34e7b).

Exactly. So I guess will proceed with directly fetching signatures from replicas, with standard DoS protection. There are way more entry points for DoS attacks beside ours.

**Comment by mrain** [comment]
Moved to https://github.com/EspressoSystems/espresso-sequencer/issues/801
