### ISSUE TITLE
[VALIDATED_STATE] - Avoid collect/copy on the encoded transaction bytes

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/HotShot#2115]
### What is this task and why do we need to work on it?

We are using `encoded_transactions.into_iter().collect()` in many places to convert an `Encode` type to a vector of bytes. We should avoid this redundant operation.

### What work will need to be done to complete this task?

There are two ways to improve this:

* Use [Cow](https://doc.rust-lang.org/std/borrow/enum.Cow.html) to reduce the redundancy.
* Update jellyfish to take an iterator over bytes to avoid the conversion.

### Are there any other details to include?

Related PR discussions:
* https://github.com/EspressoSystems/HotShot/pull/2045#discussion_r1400053762
* https://github.com/EspressoSystems/HotShot/pull/2102#discussion_r1401103511

### What are the acceptance criteria to close this issue?

We either remove the collect/copy or confirm it's necessary.

**Comment by ggutoski** [comment]
upstream issue https://github.com/EspressoSystems/jellyfish/issues/417

**Comment by ggutoski** [comment]
I think we also need to change the trait bounds for `BlockPayload::Encode` assoc type in order to enable copyless encoding. See https://github.com/EspressoSystems/espresso-sequencer/pull/1058#discussion_r1481588674
