### ISSUE TITLE
[LIBP2P] - Only walk DHT on cache misses

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2151]
### What is this task and why do we need to work on it?

Right now, when we do a Kademlia lookup, it walks for the nearest peers no matter what.
Since we do caching, this is unneeded, and it causes some issues with the timeout test by taking a long time.

We should only do these on cache misses, meaning we don't have the value.

### What are the acceptance criteria to close this issue?

- [ ] review from @DieracDelta 
- [ ] tests that incorporate this functionality

**Comment by bfish713** [comment]
I will revisit this soon, but AFAICT it's probably not a bad idea to walk the DHT on every request as this information can keep our routing up to date.  It's also possible doing this once per view is too often (we are looking up the leader in the DHT each view) and we can address refreshing routing with #2584

**Comment by bfish713** [comment]
Looks like we aren't doing this anymore, at least it's not contributing to any slowness
