### ISSUE TITLE
[FIX_CI] - Fix web_server_network test

### ISSUE THREAD

**Issue by QuentinI** [EspressoSystems/HotShot#2206]
### What is this task and why do we need to work on it?

`web_server_network` test sporadically fails in CI:
```
Message:  TEST FAILED! Results: [("Test Overall Safety Task", NotEnoughDecides { expected: 35, got: 0 })]
Location: /opt/actions-runner/_work/HotShot/HotShot/crates/testing/src/test_runner.rs:177
```
with following error making appearance in the logs:
```
Failed to send message from network task: WebServer { source: ClientError }
```

### What work will need to be done to complete this task?

Locate and fix the cause of `web_server_network` failing

### What are the acceptance criteria to close this issue?

`web_server_network` passes consistently

**Comment by shenkeyao** [comment]
@QuentinI I just found that there's another web server-related test, `test_catchup_web`, that failed locally with the same error message. Might be worth it to check if this passes after you fix `web_server_network`. 🤔

**Comment by QuentinI** [comment]
@shenkeyao I will take a look at that too, thanks
