### ISSUE TITLE
[FIX_CI] - Investigate and fix networking-related CI failures

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2211]
### What is this task and why do we need to work on it?

We have nondeterministic test failures for networking-related tests in CI.

Specifically, `test_combined_network` has a problem where all tests try to bind to the same port. This is a bigger problem on the self-hosted runner, which does not virtualize networking like the GitHub runners do.

The other failure is with the DHT in `test_timeout_libp2p`. I think that the test parameters have to be massaged, barring a rewrite/deep dive.

### What are the acceptance criteria to close this issue?

- [ ] all networking related tests pass deterministically

**Comment by shenkeyao** [comment]
There's another network-related test that failed nondeterministically: `test_timeout_web`. It's due to `NotEnoughDecides` though, so probably nothing needs to be done on the network side. Just wanted to flag this in case it's related.

**Comment by rob-maron** [comment]
Fixed the combined network nondeterminism in #2230
