### ISSUE TITLE
[TECH DEBT] - Remove the trait SignatureKey & remove key serialization

### ISSUE THREAD

**Issue by dailinsubjam** [EspressoSystems/HotShot#2328]
### What is this task and why do we need to work on it?

- We do not need `SignatureKey` anymore, it's a wrap of jellyfish key scheme.
- We can remove serialization of public key so that the key size on-chain will be smaller.
- https://github.com/EspressoSystems/HotShot/issues/2327 is blocked by this.

### What work will need to be done to complete this task?

- [x] Remove EncodedPublicKey
~~Remove the trait SignatureKey~~
- [x] Remove the wrap of QCSignKey: BLSPriveKey
- [x] Remove the wrap of QCVerKey: BLSPubKey

### Are there any other details to include?

Followup on this https://github.com/EspressoSystems/HotShot/pull/2112.

### What are the acceptance criteria to close this issue?

Unblock https://github.com/EspressoSystems/HotShot/issues/2327.

**Comment by mrain** [comment]
`SignatureKey` is still there.

**Comment by dailinsubjam** [comment]
@mrain I think we can also close this if it 1. unblock the light client work and 2. reduce the serialization size. Since the motivation of removing `SignatureKey` is these two. Although the wrapping is still here, but as we see it also serves as a bridge so keep it is good. The key question here is that do we want to remove it in the future?

**Comment by mrain** [comment]
Ahh right. Feel free to close it. We can ignore it even if it's kept open :)
