### ISSUE TITLE
[Auto benchmarks] Define which new stats we want

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2343]
### What is this task and why do we need to work on it?

We want to figure out which new stats we want; ones that would help us get more detailed benchmarking numbers. This ticket should be a discussion.

### What are the acceptance criteria to close this issue?

The discussion output is the new stats we want and what they mean. Comment those here.

**Comment by dailinsubjam** [comment]
After the discussion, these are stats we want for now:

- Potential Stats
    - Throughput (number of transactions finalized * transaction size) / run time
    - Latency
        - timestamp transactions
        - timestamp proposals
        - latency = time finalized - time received
        - avg latency = sum of all the transaction latencies / num of transactions
        - minimum latency and maximum
- Report the config file
- total of views
- failed number of view
- commit that benchmarks running
- notes field
- which kind of leader election we are running
- Standard
    - total number of nodes = 10, 50, 100, 250
    - da committee = total nodes, 10 nodes, 25%,
    - 1 run with low number of transaction
    - 1 run with a lot of transactions submitted (saturated network)
    - 1 run tx = 512b
    - 1 run tx = 4096b
    - 1 run with 100 views
    - 1 run with 1000 views
    - 1 run with just web server, 1 with just libp2p, 1 with both
