### ISSUE TITLE
[Auto benchmarks] Store previous benchmark runs

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2354]
### What is this task and why do we need to work on it?

We want a repository for previous benchmark runs. This makes it easy to compare multiple runs between each other and notice any regressions. Likely relies on https://github.com/EspressoSystems/HotShot/issues/2346 .

### What work will need to be done to complete this task?

- [x] Figure out what format to store the benchmark run outputs in 
- [ ] Make the orchestrator save these somewhere that's easy to look at

### What are the acceptance criteria to close this issue?

Orchestrator saves the benchmark outputs to a centralized repository. Either in a human readable format or with a way to easily read it into something like a chart.

**Comment by dailinsubjam** [comment]
Results are now saved in csv file with commit sha, and re-running benchmarks will not cover the previous results.
