### ISSUE TITLE
[TECH-DBET] - Add VID shares to Decide event

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#2362]
### What is this task and why do we need to work on it?

The sequencer needs to store VID shares for safety, so we need to add the VID shares to the Decide event so that the sequencer can consume the shares. 

### What work will need to be done to complete this task?

- [ ] Add VID shares to Decide event

### What are the acceptance criteria to close this issue?

- [ ] Sequencer successfully consumes VID shares through the Decide event

**Comment by bfish713** [comment]
Duplicate
