### ISSUE TITLE
[BUILDER] - Add builder pub key to `Leaf`

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/HotShot#2389]
### What is this task and why do we need to work on it?

For whole-block atomicity, rollups need to know the identity of the builder of a block so that they can exclude transactions which requested a different builder.

### What work will need to be done to complete this task?

We need to discuss the best way to support this. Thinking about it, it seems consensus could actually be responsible for verifying the builder signature, saving the rollups that work, and honest nodes will only sign a leaf where the builder public key is correct.

Thus, perhaps we could add an optional builder signature as part of the proposal, and replicas would check it against the pub key in the proposed leaf. In the default case, the signature could be omitted and the "builder" pub key could be the same as the proposer.

### What are the acceptance criteria to close this issue?

HotShot leaves contain a builder pub key, and it is guaranteed that this key has signed the committed block hash.

**Comment by elliedavidson** [comment]
We'll prioritize this after we have a simple builder integrated into HotShot.

**Comment by jbearer** [comment]
As discussed [today](https://www.notion.so/espressosys/c964feb5698942dbb8a1620e06210cc6), we will do this in the sequencer
