### ISSUE TITLE
[TECH_DEBT] - delete state_map in RoundResult

### ISSUE THREAD

**Issue by DieracDelta** [EspressoSystems/HotShot#2435]
### What is this task and why do we need to work on it?

State is now `()`. We don't use it, and it's not useful. Drop the safety check and tracked state from `RoundResult`.

### What are the acceptance criteria to close this issue?

`state_map` is dropped from `RoundResult`

**Comment by shenkeyao** [comment]
Thanks for making the issue! I'll work on this as part of the validated state tasks.
