### ISSUE TITLE
[TECH_DEBT] - Don't Sleep When Waiting for Message

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#2558]
### What is this task and why do we need to work on it?

The network task does this:
```
    let direct_handle = async_spawn(async move {
        loop {
            let msgs = match network.recv_msgs(TransmitType::Direct).await {
                Ok(msgs) => Messages(msgs),
                Err(err) => {
                    error!("failed to receive direct messages: {err}");

                    // return zero messages so we sleep and try again
                    Messages(vec![])
                }
            };
            if msgs.0.is_empty() {
                async_sleep(Duration::from_millis(100)).await;
            } else {
                state.handle_messages(msgs.0).await;
            }
        }
    });
```
Ideally `recv_messages` would not be able to return an empty vector.
Sadly the web server implementation uses locked vectors for it's message queues so we can't simply `await` for the next message, we have to periodically check the queue.  

### What work will need to be done to complete this task?

Either simply remove the sleep case and just await in a loop when we get rid of the webserver, or fix the webserver impl to use channels where it should.

### What are the acceptance criteria to close this issue?

No sleeps in this code

**Comment by QuentinI** [comment]
@rob-maron @bfish713 stumbled upon this one, can we remove the sleep now?
