### ISSUE TITLE
[BUILDER] - Allow builders to listen for DA streams but not vote on them

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#2636]
### What is this task and why do we need to work on it?

Builders (and perhaps other nodes in the future) need to listen to DA proposals, and therefore be sent DA proposals as if they were on the DA committee.  However, they won't vote, so they should not be counted towards the DA committee quorum.  

### What work will need to be done to complete this task?

Proposed Design: 
* At startup, allow nodes to signal what they want to listen for.  If they want to listen for DA proposals but they are not on the DA committee, they can signal this through some set up configuration.  

### Are there any other details to include?

In the future we'll need to somehow prioritize DA traffic to those that need it most, but that is out of scope for this sprint. 

cc @nyospe and @move47 for visibility

### What are the acceptance criteria to close this issue?

Successfully run a test with a builder node receiving DA data but not voting.

**Comment by move47** [comment]
Some work was done in #2721

**Comment by bfish713** [comment]
I think we proved this is completed with the tests
