### ISSUE TITLE
[CX_CLEANUP] - Create a new pared down Consensus module.

### ISSUE THREAD

**Issue by jparr721** [EspressoSystems/HotShot#3170]
### What is this task and why do we need to work on it?

We need a new separate consensus module that will exist alongside the existing consensus module to achieve our goals of removing the old logic. This will enable us to build the features in isolation without needing to fight against merge conflicts and bug fixes as we stabilize for Cappuccino.

### What work will need to be done to complete this task?

- [ ] Create the new Consensus task under the name `consensus2`.
- [ ] Add a flag toggle to `hotshot/lib.rs` to enable it alongside the other dependency tasks.

### Are there any other details to include?

This one might not need exhaustive testing yet since it should essentially just handle vote tabulation, which we can definitely take 1:1 with the existing consensus task.

### What are the acceptance criteria to close this issue?

New task is added and the tests pass.

**Comment by shenkeyao** [comment]
Closed by #3149
