### ISSUE TITLE
Can `BlockContents::hash_leaf` be made more-explicitly-typed?

### ISSUE THREAD

**Issue by tri-joe** [EspressoSystems/HotShot#338]
Currently `espresso` implements `hash_leaf` by abusing some internal behavior of `commit` (https://github.com/EspressoSystems/espresso/blob/2e74f21d54ee02022a93fcafed66f549f9bc9abd/zerok/zerok_lib/src/state.rs#L194). It needs to do that because `hash_leaf` is only given `&[u8]`, which doesn't seem like the right type for this to receive. I'm not sure the best way to update the trait, but it feels like there must be something that preserves more information.

cc @nmccarty @jbearer

**Comment by DieracDelta** [comment]
Closed because now we use the Committable trait and get all the nice type safety perks of using actual types
