### ISSUE TITLE
[CX-Marketplace] - Remove Payload and Metadata from Builder Signature Key

### ISSUE THREAD

**Issue by jparr721** [EspressoSystems/HotShot#3410]
### What is this task and why do we need to work on it?

We need to remove the Payload and Metadata requirement from the builder signature in  `HotShot/crates/types/src/traits/signature_key.rs`. We need to keep the existing function for backwards compatibility, so we can take the below function:
```rust
    fn sign_fee<Metadata: EncodeBytes>(
        private_key: &Self::BuilderPrivateKey,
        fee_amount: u64,
        metadata: &Metadata,
        vid_commitment: &<VidSchemeType as VidScheme>::Commit,
    ) -> Result<Self::BuilderSignature, Self::SignError> {
        Self::sign_builder_message(
            private_key,
            &aggregate_fee_data(fee_amount, metadata, vid_commitment),
        )
    }

```

And add a new one:
```rust
    fn sign_fee_marketplace<Metadata: EncodeBytes>(
        private_key: &Self::BuilderPrivateKey,
        fee_amount: u64,
    ) -> Result<Self::BuilderSignature, Self::SignError> {
        Self::sign_builder_message(
            private_key,
            &aggregate_fee_data(fee_amount),
        )
    }

```

The name can be anything.

### Are there any other details to include?

Make sure to tag @jbearer and @tbro on the PR to have them double check that it's what they expect.

### What are the acceptance criteria to close this issue?

Tests pass for the new method along the upgrade path.

**Comment by tbro** [comment]
Possibly obvious... but just so we don't miss it in the rush... we will need an analogue of the above but for `validate_fee_signature`.  

```
    /// validate signature over marketplace fee information with the builder's public key
    fn validate_marketplace_fee_signature<Metadata: EncodeBytes>(
        &self,
        signature: &Self::BuilderSignature,
        fee_amount: u64,
    ) -> bool {
        self.validate_builder_signature(
            signature,
            &aggregate_fee_data(fee_amount, metadata, vid_commitment),
        )
    }

```
