### ISSUE TITLE
[Byzantine testing] - Make byzantine integration tests work with `tokio`

### ISSUE THREAD

**Issue by ss-es** [EspressoSystems/HotShot#3440]
### What is this task and why do we need to work on it?

Currently, running byzantine nodes with `tokio` in integration tests causes timing issues during shutdown. While nodes function correctly, after shutdown consensus tasks get stuck in a loop trying to receive events from a closed channel, causing the test to hang.

### What are the acceptance criteria to close this issue?

Byzantine integration tests pass with `tokio`

**Comment by shamb0** [comment]
Hi @ss-es

I am interested to pickup this task, Could you please assign it to me ?

Thanks

**Comment by ss-es** [comment]
@shamb0 sorry, I didn't see this message at all until just now!

marking closed in #3535

**Comment by shamb0** [comment]
> @shamb0 sorry, I didn't see this message at all until just now!

Thanks, `@ss-es`. No worries at all! I completely understand you're on a tight schedule.
