### ISSUE TITLE
[TESTING] - Investigate Restart Test Failures

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#3651]
### What is this task and why do we need to work on it?

test_all_restart_one_da has been very flaky on CI
What we know so far:
1.) There is some timing issue on startup, causing some nodes to timeout on view 1 at first then eventually view passes
2.) When view 1 is timing out initially this causes some of our logic to fail and we get a subtraction overflow
3.) Lowering the next_view_timeout causes some random views to fail, see if we can find the bottleneck or bug

### What work will need to be done to complete this task?

Investigate the 3 issues above, for the subtraction overflow it is a pretty easy fix to get the test from crashing but still want to know why we are getting into this scenario with shorter view timeouts

### What are the acceptance criteria to close this issue?

No flaky restart tests

**Comment by lukeiannucci** [comment]
pr1: some cleanup to prevent overflow
https://github.com/EspressoSystems/HotShot/pull/3668#pullrequestreview-2298091366
