### ISSUE TITLE
[EPOCH TRANSITION] - a new config field for epoch height

### ISSUE THREAD

**Issue by lukaszrzasik** [EspressoSystems/HotShot#3728]
### What is this task and why do we need to work on it?

A new config field needs to be added to specify the height of an epoch. Epoch's height is measured in number of blocks. A value of zero should be interpreted as: there are no epochs, there is only one static stake table.

### What are the acceptance criteria to close this issue?

A new config field is added to that specified the height of an epoch. The default value should be set to zero so that the current code can run without problems.

**Comment by ss-es** [comment]
Completed in #3751
