### ISSUE TITLE
Membership trait changes to support PoS

### ISSUE THREAD

**Issue by pls148** [EspressoSystems/HotShot#3966]
Reference [meeting notes](https://www.notion.so/espressosys/PoS-Membership-Trait-Discussion-15b2431b68e9803f8c96cbae9fa3a1ad?pvs=4)

- [x] HotShot clones the Membership object when receiving it, wrapping it in `Arc<RwLock<>>`
- [x] Remove requirement for Membership to implement Clone
- [x] Add sync_l1 and add_epoch_root functions, which return an Option<FnOnce(&mut Membership)> or similar. Functions should be called with a read lock held, then upgrade to write lock if a callback is returned. Default implementations should return None. A static helper function can be used to indicate if each function should be called at all.
- Convert the existing Membership methods to async (NOT NEEDED ANY MORE)
- [ ] Audit existing code to avoid Membership calls while holding other locks

**Comment by sveitser** [comment]
>  Convert the existing Membership methods to async

@pls148 I think this is not needed anymore.
