### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by LaplaceFox** [EspressoSystems/HotShot#863]
[hotshot.docs.espressosys.com/](https://hotshot.docs.espressosys.com/) is currently a 404 (@Ancient123)

**Comment by Ancient123** [comment]
So the redirect from index doesn't seem to be functional anymore.
https://github.com/EspressoSystems/HotShot/blob/main/.github/workflows/doc.yml#L45

There doesn't seem to be a hotshot directory in the generated HTML branch
( https://github.com/EspressoSystems/HotShot/tree/gh-pages )

We need to direct it to somewhere that exists.

**Comment by Ancient123** [comment]
@jbearer : Can I get a recommendation on this?

**Comment by jbearer** [comment]
It's working again
