### ISSUE TITLE
Optimize Nginx and web server benchmakrs

### ISSUE THREAD

**Issue by kmchicoine** [EspressoSystems/HotShot#912]
Find and fix slowdowns in web server and Nginx, with a goal of beating the old centralized server and having Nginx improve performance with large numbers of nodes

**Comment by elliedavidson** [comment]
Closing in favor of more specific issues: 
https://github.com/EspressoSystems/HotShot/issues/944
https://github.com/EspressoSystems/HotShot/issues/945
https://github.com/EspressoSystems/HotShot/issues/946
https://github.com/EspressoSystems/HotShot/issues/947
https://github.com/EspressoSystems/HotShot/issues/948
https://github.com/EspressoSystems/HotShot/issues/949
