### ISSUE TITLE
Refactor `NodeType`

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#929]

**Comment by shenkeyao** [comment]
Planning: https://www.notion.so/espressosys/DA-Refactoring-Planning-e6d31ebde1b64987baae04320a03b053?pvs=4#f0c6b37d3ee14210a1864a793160c388

**Comment by shenkeyao** [comment]
The `NodeImplementation` refactor may end up updating `NodeType` as well, but the main changes needed for `NodeType` are done, so closing this issue.
